### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found. - cudnn_adv_infer64_8.dll

### ISSUE THREAD

**Issue by JamesLAVFX** [sashaok123/LoRA-EXTRACTOR#7]
Getting this issue preventing extraction: 

`Extraction:
Traceback (most recent call last):
  File "C:\Users\RenderNode\Downloads\LoRA EXTRACTOR\lib\extract_LoRA_from_models.py", line 7, in <module>
    import torch
  File "C:\Users\RenderNode\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\__init__.py", line 139, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\RenderNode\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\lib\cudnn_adv_infer64_8.dll" or one of its dependencies.`

File is there, just can't seem to load it?

**Comment by JamesLAVFX** [comment]
Nevermind, fixed with a reinstall of Pytorch.
